# Generated by Django 4.0.2 on 2022-06-11 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0004_alter_identifiedcomment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentifiedComment',
            new_name='IdComment',
        ),
        migrations.RenameModel(
            old_name='IdentifiedPost',
            new_name='IdPost',
        ),
    ]
